global:
  checkNewVersion: true
  sendAnonymousUsage: true
serversTransport:
  insecureSkipVerify: true
  forwardingTimeouts:
    dialTimeout: 42s
    responseHeaderTimeout: 42s
    idleConnTimeout: 42s
entryPoints:
  web:
    address: ":80"
    transport:
      respondingTimeouts:
        readTimeout: 42s
        writeTimeout: 42s
        idleTimeout: 42s
    proxyProtocol:
      insecure: true
    forwardedHeaders:
      insecure: true
  websecure:
    address: ':443'
    http:
      tls: {}
    transport:
      respondingTimeouts:
        readTimeout: 42s
        writeTimeout: 42s
        idleTimeout: 42s
      proxyProtocol:
        insecure: true
      forwardedHeaders:
        insecure: true
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false
    useBindPortIP: true
    network: tunnel
    swarmMode: false
    httpClientTimeout: 300
  file:
    watch: true
    filename: "/config/dynamic_config.yaml"
