version: '3.1'
services:
  rclone:
    image: rclone/rclone
    user: "0"
    restart: always
    command: rcd --rc-web-gui --rc-addr :5572 --rc-no-auth --log-file /logs/rclone.log --rc-web-gui-no-open-browser
    networks:
      - tunnel
    ports:
      - 5572:5572
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rclone.entrypoints=web,websecure"
      - "traefik.http.routers.rclone.rule=Host(`rclone.ocproxy.net`)"
      - "traefik.http.services.rclone-service.loadbalancer.server.port=5572"
    volumes:
      - /opt/docker-apps/n8n/rclone_app/conf:/config/rclone
      - /opt/docker-apps/n8n/rclone_app/logs:/logs
      - /opt/docker-apps/n8n/rclone_app/data:/data
    environment:
      - PHP_TZ=America/Chicago
      - PUID=1000
      - PGID=1000
  postgres:
    image: postgres:11
    restart: always
    networks:
      - default
      - tunnel
    ports:
      - 127.0.0.1:54320:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
      - n8nPGVolume:/var/lib/postgresql/data
  n8n:
    image: ocdev.azurecr.io/n8n-custom:latest
    restart: always
    user: "0"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.entrypoints=web,websecure"
      - "traefik.http.routers.n8n.rule=Host(`n8n.ocproxy.net`)"
      - "traefik.http.routers.n8n.service=n8n-service"
      - "traefik.http.services.n8n-service.loadbalancer.server.port=5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=false
      - EXECUTIONS_DATA_SAVE_ON_ERROR=all
      - EXECUTIONS_DATA_SAVE_ON_SUCCESS=all
      - EXECUTIONS_DATA_SAVE_ON_PROGRESS=true
      - N8N_METRICS=true
      - N8N_EMAIL_MODE=smtp
      - N8N_SMTP_HOST=172.16.12.128
      - N8N_SMTP_PORT=2525
      - N8N_SMTP_SSL=false
      - N8N_SMTP_USER=admin
      - N8N_SMTP_PASS=pass
      - N8N_SMTP_SENDER=noreply@outdoorcap.com
      - N8N_VERSION_NOTIFICATIONS_ENABLED=false
      - NODE_FUNCTION_ALLOW_EXTERNAL=moment,lodash
      - NODE_FUNCTION_ALLOW_BUILTIN=*
      - N8N_CUSTOM_EXTENSIONS=/custom_nodes
      - GENERIC_TIMEZONE=America/Chicago
      - N8N_HIRING_BANNER_ENABLED=false
      - N8N_EDITOR_BASE_URL=https://n8n.ocproxy.net
      - WEBHOOK_URL=https://n8n.ocproxy.net/
      - N8N_HOST=n8n.ocproxy.net
    ports:
      - 5678:5678
    links:
      - postgres
    networks:
      - default
      - tunnel
    volumes:
      - /opt/docker-apps/n8n/logs:/n8n_logs
      - /opt/docker-apps/n8n/n8n_config:/home/node/.n8n
      - /opt/docker-apps/n8n/n8n_data:/n8n_data
      - /opt/docker-apps/n8n/n8n_nodes:/custom_nodes
    command: /bin/sh -c "sleep 5; /data/packages/cli/bin/n8n start"

volumes:
  n8nPGVolume:
    external: true

networks:
  default:
    internal: true
  tunnel:
    external: true
