version: '3'

services:
  tunnel:
    container_name: cloudflare_tunnel
    image: cloudflare/cloudflared:latest
    restart: always
    command:
      - "tunnel run"
    networks:
      - tunnel
      - default
    volumes:
      - ./cloudflare_config:/etc/cloudflared
  traefik:
    image: "traefik:v2.6"
    container_name: "traefik"
    networks:
      - tunnel
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.ocproxy.net `) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.routers.dashboard.service=api@internal"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik_config/config/config.yaml:/etc/traefik/traefik.yml"
      - "./traefik_config/config/dynamic_config.yaml:/config/dynamic_config.yaml"
      - "./traefik_config/certs:/certs"
networks:
  tunnel:
    external: true
  default:
    internal: true
