version: '3'

services:
  tunnel:
    container_name: cloudflare_tunnel
    user: "0"
    image: cloudflare/cloudflared:latest
    restart: always
    command: tunnel --logfile /logs/cloudflared.log --loglevel info --transport-loglevel info run
    networks:
      - tunnel
      - default
    volumes:
      - ./cloudflare_config:/etc/cloudflared
      - /opt/docker-apps/proxy/cloudflare_logs:/logs
  traefik:
    restart: always
    image: "traefik:v2.6"
    container_name: "traefik"
    user: "0"
    environment:
      - TZ=America/Chicago
    networks:
      - tunnel
      - default
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dashboard.rule=Host(`traefik.ocproxy.net `) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))"
      - "traefik.http.services.dashboard-service.loadbalancer.server.port=8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/opt/docker-apps/proxy/traefik_logs:/logs"
      - "./traefik_config/config/config.yaml:/etc/traefik/traefik.yml"
      - "./traefik_config/config/dynamic_config.yaml:/config/dynamic_config.yaml"
      - "./traefik_config/certs:/certs"
networks:
  tunnel:
    external: true
  default:
    internal: true
